format_version: 10
pipelines:
  practice-expense-terraform2-apply:
    group: terraform
    materials:
      git-da613e5:
        git: https://github.com/raju-b70/practice-expense-terraform2.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec: {command:terraform, arguments: ["init", "-backend-config=env-dev/state.tfvars" ], run_if: passed
                - exec: {command:terraform, arguments: ["apply", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed